version: '3.1'

services:

  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: busreservation
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
